name: CI Workflow

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      # Install Node.js
      - name: Set up Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 16  # or the version you prefer

      # Install Angular CLI
      - name: Install Angular CLI
        run: npm install -g @angular/cli

      # Build Angular project
      - name: Build Angular project
        run: ng build --configuration=production

      # Package and upload artifact
      - name: Package
        run: |
          mkdir -p ${{ github.workspace }}/publish_zip
          cd ${{ github.workspace }}/dist
          zip -r ${{ github.workspace }}/publish_zip/publish.zip *

      - name: Upload artifact
        uses: actions/upload-artifact@v2
        with:
          name: publish
          path: ${{ github.workspace }}/publish_zip/publish.zip
