
name: CI/CD Workflow

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Use Node.js 18.x
        uses: actions/setup-node@v3
        with:
          node-version: '18.x'

      - name: Install Angular CLI
        run: npm install -g @angular/cli

      - name: Install dependencies
        run: npm install

      - name: Build Angular project
        run: ng build --configuration=production

      - name: Package
        run: |
          mkdir -p ${{ github.workspace }}/publish
          cd ${{ github.workspace }}/docs
          zip -r ${{ github.workspace }}/publish/publish_docs.zip .

      - name: Upload artifact
        uses: actions/upload-artifact@v2
        with:
          name: publish
          path: ${{ github.workspace }}/publish

  deploy:
    runs-on: ubuntu-latest
    needs: build
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Download artifact
        uses: actions/download-artifact@v2
        with:
          name: publish
          path: ${{ github.workspace }}/publish

      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GH_TOKEN }}
          publish_dir: ${{ github.workspace }}/publish
          cname: https://pradipdj432.github.io/DK-Engineer  # Optional: Add your custom domain if applicable

