name: CI Workflow

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      # Add any necessary setup steps here

      - name: Use Node.js 18.x
        uses: actions/setup-node@v3
        with:
          node-version: '18.x'

      - name: Install Angular CLI
        run: npm install -g @angular/cli

      - name: Install dependencies
        run: npm install

      - name: Build Angular project
        run: ng build --configuration=production

      - name: Package
        run: |
          mkdir -p ${{ github.workspace }}/publish_zip
          cd dist  # Assuming 'dist' is the folder containing build artifacts
          zip -r ${{ github.workspace }}/publish_zip/publish.zip .

      - name: Upload artifact
        uses: actions/upload-artifact@v2
        with:
          name: publish
          path: ${{ github.workspace }}/publish_zip/publish.zip 

      - name: Download artifact
        if: success() && steps.build.outcome == 'success'
        uses: actions/download-artifact@v2
        with:
          name: publish
          path: ${{ github.workspace }}/publish_zip
