name: CI Workflow

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Setup Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '18' # or any other version compatible with Angular CLI

      - name: Install Angular CLI
        run: npm install -g @angular/cli

      - name: Install project dependencies
        run: npm install

      - name: Build Angular project
        run: ng build --configuration=production

      - name: Package
        run: |
          mkdir -p ${{ github.workspace }}/publish_zip
          cd ${{ github.workspace }}/dist
          zip -r ${{ github.workspace }}/publish_zip/publish.zip .

      - name: Upload artifact
        uses: actions/upload-artifact@v2
        with:
          name: publish
          path: ${{ github.workspace }}/publish_zip/publish.zip 

      - name: Download artifact
        if: success() && steps.build.outcome == 'success'
        uses: actions/download-artifact@v2
        with:
          name: publish
          path: ${{ github.workspace }}/publish_zip
